[package]
name = "lestallum-web"
version = "0.1.0"
edition = "2021"
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos = { version = "0.8.0" }
leptos_router = { version = "0.8.0" }
axum = { version = "0.8.0", optional = true }
console_error_panic_hook = { version = "0.1", optional = true }
js-sys = "0.3"
leptos_axum = { version = "0.8.0", optional = true }
leptos_meta = { version = "0.8.0" }
lestallum-api = { path = "../api", optional = true }
shared = { path = "../shared", optional = true }
tokio = { version = "1", features = ["net"], optional = true }
wasm-bindgen = "0.2.106"
web-sys = { version = "0.3", features = [
    "Element",
    "IntersectionObserver",
    "IntersectionObserverEntry",
    "MouseEvent",
    "Window",
] }
tracing = "0.1"

[features]
hydrate = ["leptos/hydrate", "dep:console_error_panic_hook"]
ssr = [
    "dep:axum",
    "dep:lestallum-api",
    "dep:shared",
    "dep:tokio",
    "dep:leptos_axum",
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
]
